sudo: false
language: ruby
cache: bundler
rvm:
- 2.2.2
services:
- memcached
before_install:
- gem install bundler
before_script:
- bundle install
- psql -c 'create database epets_test;' -U postgres
- RAILS_ENV=test bundle exec rake db:structure:load
script: bundle exec rake
env:
